### ISSUE TITLE
Stock amount is not reduced after On-Hold status

### ISSUE THREAD

**Issue by h-nasu** [paysbuy/psb-woocommerce2.3#1]
This depends on site admin but as default, stock amount should be reduced after the payment is finished on Paysbuy and order status is On-Hold. Below is the Woocommerce document for reference.

**On-Hold** – Awaiting payment – stock is reduced, but you need to confirm payment
**Processing** – Payment received and stock has been reduced – the order is awaiting fulfillment. All product orders require processing
**Completed** – Order fulfilled and complete – requires no further action
（source: [https://docs.woocommerce.com/document/managing-orders/](https://docs.woocommerce.com/document/managing-orders/)）

Payment Method: Check Payment (default payment method from woocommerce)
File: wp-content/plugins/woocommerce/includes/gateways/cheque/class-wc-gateway-cheque.php
```
public function process_payment( $order_id ) {

  $order = wc_get_order( $order_id );

  // Mark as on-hold (we're awaiting the cheque)
  $order->update_status( 'on-hold', _x( 'Awaiting check payment', 'Check payment method', 'woocommerce' ) );

  // Reduce stock levels
  $order->reduce_order_stock();

....
```
Woocommerce default payment methods include "$order->reduce_order_stock();" which seem as function that reduces the stock amount, but current Paysbuy plugin do not have this. I have put the code as below and seems working as expected.
```
else if ($result == '02'){
  $order->update_status('on-hold', __('Awaiting Counter Service payment', 'woothemes'));
　// Reduce stock levels
　$order->reduce_order_stock();
  $woocommerce->cart->empty_cart();
}
```

**Comment by jon-paysbuy** [comment]
OK - this is does seem to be an oversight on the part of the developer who originally wrote our plugin. Do you think you could fork the project and submit this change as a pull request? Thanks

**Comment by h-nasu** [comment]
Sure thing.
I edited the fill and send you the pull request already.
